---
# tasks file for ansible-role-apache/
- name: install apache
  apt:
    name:   apache2
    state:  latest

- name: apache2 service state
  service:
    name:     apache2
    state:    started
    enabled:  yes
